/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/Admin/AsideMenu.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    CommentCard: typeof import('./src/components/CommentCard.vue')['default']
    CommentSmall: typeof import('./src/components/News/CommentSmall.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/Header.vue')['default']
    HotNews: typeof import('./src/components/News/HotNews.vue')['default']
    Menu: typeof import('./src/components/Admin/Menu.vue')['default']
    MenuAside: typeof import('./src/components/Admin/MenuAside.vue')['default']
    MenuView: typeof import('./src/components/Admin/MenuView.vue')['default']
    MenuViews: typeof import('./src/components/Admin/MenuViews.vue')['default']
    NewsAside: typeof import('./src/components/News/NewsAside.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    NewsComment: typeof import('./src/components/NewsComment.vue')['default']
    NewsCommentCard: typeof import('./src/components/NewsCommentCard.vue')['default']
    NewsCommentView: typeof import('./src/components/NewsCommentView.vue')['default']
    NewsDetail: typeof import('./src/components/News/NewsDetail.vue')['default']
    'NewsDetail废弃': typeof import('./src/components/NewsDetail废弃.vue')['default']
    NewsHeader: typeof import('./src/components/News/NewsHeader.vue')['default']
    NewsMain: typeof import('./src/components/News/NewsMain.vue')['default']
    PasswordInput: typeof import('./src/components/Login/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsernameInput: typeof import('./src/components/Login/UsernameInput.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
